import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F6F1',
  },
  contentContainer: {
    padding: 20,
    paddingBottom: 40,
    gap: 8,
  },
  title: {
    fontFamily: Platform.select({ ios: 'Georgia', android: 'serif' }),
    fontSize: 26,
    fontWeight: 'bold',
    color: '#2F4A2C',
  },
  subtitle: {
    fontSize: 14,
    color: '#7C8A75',
    lineHeight: 20,
    marginTop: 6,
    marginBottom: 4,
  },

  tipCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8DB',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 6,
    marginBottom: 4,
  },
  tipText: {
    flex: 1,
    fontSize: 12.5,
    color: '#6E7D67',
    lineHeight: 17,
  },

  // Grid
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  tile: {
    width: '48%',
    minHeight: 96,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E7ECE1',
    shadowColor: '#3C463A',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  tileIcon: {
    width: 36,
    height: 36,
    borderRadius: 11,
    backgroundColor: '#E6ECE0',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  tileEmoji: {
    fontSize: 22,
  },
  tileLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#3C463A',
  },
  tileHint: {
    fontSize: 12,
    color: '#93A089',
    marginTop: 2,
  },

  // Add tile
  addTile: {
    width: '48%',
    minHeight: 96,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#C4CDBA',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  addPlus: {
    fontSize: 24,
    color: '#6E7D67',
  },
  addText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6E7D67',
  },

  // Modal
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(44,42,38,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 28,
  },
  modalCard: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    gap: 12,
    borderWidth: 1,
    borderColor: '#E7ECE1',
    shadowColor: '#3C463A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#3C463A',
  },
  emojiSection: {
    alignItems: 'center',
    marginVertical: 4,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#3C463A',
  },
  input: {
    backgroundColor: '#F4F6F1',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    color: '#3C463A',
    borderWidth: 1,
    borderColor: '#DCE4D5',
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: '#EEF1EA',
    paddingVertical: 11,
    borderRadius: 10,
    alignItems: 'center',
  },
  cancelButtonText: {
    color: '#6E7D67',
    fontSize: 15,
    fontWeight: '600',
  },
  saveButton: {
    flex: 1,
    backgroundColor: '#8FB07A',
    paddingVertical: 11,
    borderRadius: 10,
    alignItems: 'center',
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: 'bold',
  },
  deleteButton: {
    backgroundColor: '#FFFFFF',
    borderColor: '#C44536',
    borderWidth: 1,
    paddingVertical: 11,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 2,
  },
  deleteButtonText: {
    color: '#C44536',
    fontSize: 14,
    fontWeight: '600',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  catalogScroll: {
    maxHeight: 320,
  },
  catalogRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF1EA',
  },
  catalogIcon: {
    width: 38,
    height: 38,
    borderRadius: 11,
    backgroundColor: '#F1F4EE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  catalogLabel: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#3C463A',
  },
  emptyText: {
    fontSize: 14,
    color: '#93A089',
    textAlign: 'center',
    paddingVertical: 24,
  },
  toast: {
    position: 'absolute',
    bottom: 110,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#5E8C4A',
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderRadius: 999,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  toastText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
});
