import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        height: '100%',
        width: '100%',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
     //   backgroundColor: 'red',
        paddingBottom: 10,
    },
    profile: {
        backgroundColor: '#FFF',
        height: 60,
        width: 60,
        borderRadius: 50,
        justifyContent: 'center',
        alignItems: "center",
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
        elevation: 8,
    },
    headerBtns: {
        flexDirection: 'row',
    },
    volume: {
        marginRight: 10,
    },
    topDisplay: {
      //  backgroundColor: 'green',
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingTop: 10
    },
    topDisplayLeft: {
    //    backgroundColor: "grey",
        paddingLeft: 25,
        alignSelf: 'flex-start',
    },
    topDisplayRight: {
      //  backgroundColor: 'blue',
        paddingRight: 20,
    },
    moodTrackerBtn: {
        backgroundColor: 'rgba(40, 145, 220, 0.2)',
        borderWidth: 1,
        borderColor: "#FFF",
        borderRadius: 20,
        paddingVertical: 5,
        paddingHorizontal: 10,
        marginTop: 5,
    },
    InterBold: {
        fontFamily: "InterBold",
    },
    coin: {
    //    backgroundColor: "white",
        marginTop: 10,
        paddingVertical: 5,
    },
    coinImage: {
        height: 30,
        width: 28,
        position: 'absolute',
    },
    coinBar: {
        backgroundColor: "#FCF4D2",
        borderColor: "#5E4833",
        borderWidth: 2,
        borderRadius: 20,
        paddingVertical: 1,
        paddingLeft: 20,
        paddingRight: 15,
        marginLeft: 10,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'flex-start'
    },
    xp: {
     //   backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'flex-end',
        paddingVertical: 10,
        paddingHorizontal: 15,
        marginTop: 30,
    },
    xpTop: {
        backgroundColor: '#FCF4D2',
        borderWidth: 4,
        borderRadius: 50,
        borderColor: "#5E4833",
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 5,
        paddingHorizontal: 14,
        position: 'absolute',
        top: 0,
        alignSelf: 'center',
    },
    xpBarOuter: {
        borderWidth: 4,
        borderRadius: 20,
        borderColor: '#5E4833',
        backgroundColor: '#FCF4D2',
       // alignSelf: 'flex-start',
        marginTop: 30,
        paddingHorizontal: 4,
        paddingBottom: 5,
        paddingTop: 7,
    },
    xpBarInner: { 
        height: 180,
        width: 30,
        backgroundColor: '#FCF4D2',
        borderRadius: 20,
        overflow: 'hidden' 
    },
    pet: {
     //  backgroundColor: 'purple',

    },
    petName: {
        backgroundColor: "#FFF", 
        borderWidth: 4, 
        borderRadius: 20, 
        borderColor: '#025673',
        alignItems: 'center',
        justifyContent: 'center'
    },
    bottomDisplay: {
    //    backgroundColor: 'red',
        flexDirection: 'row',
        marginTop: 'auto',
        marginBottom: 130,
    },
    gameBtns: {
        backgroundColor: '#FCF4D2',
        borderColor: '#5E4833',
        borderWidth: 3,
        borderRadius: 50,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 5,
        paddingHorizontal: 5,
        marginVertical: 2 
    },
    focusContainer: {
      //  backgroundColor: 'black',
        paddingHorizontal: 10,
    },
    focusSession: {
        backgroundColor: 'rgba(11, 77, 101, 0.7)',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 20,
        marginBottom: 10,
        alignSelf: 'center',
        paddingVertical: 5,
        paddingHorizontal: 15,
    },
    timer: {
        backgroundColor: 'rgba(255, 255, 255, 0.7)',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 5,
        paddingHorizontal: 20,
        borderRadius: 20,
    },
    gameBtnsColumn: {
    flex: 1,
    paddingLeft: 20,
    alignItems: 'flex-start',
    justifyContent: 'center',
    },
});